version: 0.2

phases:
  build:
    commands:
       - npm install
       - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://my-demo-pipeline-20240506/code/nodejs/
  artifacts:
  # include all files required to run the application
    files:
      - public/**/*
      - src/**/*
      - package.json
      - appspec.yml
      - scripts/**/*
